In [3]:
import pandas as pd

In [6]:
df = pd.read_csv("mabel.txt", header=None, encoding='utf8', on_bad_lines='skip')

In [7]:
df

           0                                                  1
0   05/12/19   1:42 pm - Messages to this chat and calls are...
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [8]:
df=df.drop(0)

In [9]:
df.columns=['Date','Chat']

In [10]:
df

        Date                                               Chat
1   05/12/19   1:42 pm - Mabel Infoziant: Hi this is Mabel w...
2   05/12/19   1:42 pm - Mabel Infoziant: What’s your full name
3   05/12/19                      1:42 pm - AR❤: Ramisha Rani K
4   05/12/19                      1:42 pm - Mabel Infoziant: Ok
5   05/12/19   1:42 pm - Mabel Infoziant: ramisharanik@gmail...
6   05/12/19          1:43 pm - Mabel Infoziant: Your email Id?
7   05/12/19                             1:43 pm - AR❤: Yes Mam
8   05/12/19   1:43 pm - Mabel Infoziant: I will send 2 abst...
9   05/12/19                            1:43 pm - AR❤: Yeah mam
10  05/12/19   1:43 pm - Mabel Infoziant: Give me the list t...
11  05/12/19   1:43 pm - Mabel Infoziant: Send me cbe office...
12  05/12/19   1:44 pm - AR❤: Yeah Mam within Evening I will...
13  05/12/19   1:45 pm - AR❤: Tomorrow I have to visit the o...
14  05/12/19                      1:48 pm - Mabel Infoziant: ok
15  05/12/19   1:48 pm - Mabel Infoziant: send the details o...
16  05/12/19   1:49 pm - AR❤: Sure mam. Soon I will share de...
17  05/12/19   2:00 pm - AR❤: I have read the Abstract mam. ...
18  05/12/19   2:04 pm - Mabel Infoziant: I think Vignesh ha...
19  05/12/19   2:04 pm - Mabel Infoziant: I have sent the ab...
20  05/12/19                              2:06 pm - AR❤: Ok mam
21  05/12/19   2:07 pm - AR❤: I have read both the abstract ...
22  05/12/19   4:44 pm - Mabel Infoziant: Yes we need to ya ...
23  05/12/19                           4:48 pm - AR❤: Sure mam.
24  05/12/19                   8:07 pm - AR❤: Shall I call mam?
25  08/12/19   10:45 pm - Mabel Infoziant: Hi I was at churc...
26  08/12/19                         11:52 pm - AR❤: It's k mam
27  08/12/19   11:55 pm - AR❤: Just to know the tomorrow pla...
28  09/12/19    12:09 pm - AR❤: Mam can u send Vignesh number??
29  09/12/19   12:13 pm - Mabel Infoziant: Vignesh ML Infozi...
30  09/12/19   12:23 pm - Mabel Infoziant: I was in a meetin...
31  09/12/19                    12:25 pm - AR❤: Can I cal u mam
32  09/12/19   12:26 pm - AR❤: Waiting for u r finalization ...
33  09/12/19   12:26 pm - AR❤: If we finiliaze I can work wi...
34  09/12/19   12:28 pm - AR❤: So what ever may be ..if you ...
35  09/12/19           12:28 pm - AR❤: You deleted this message
36  09/12/19                     12:29 pm - AR❤: Do the needful
37  09/12/19   12:41 pm - Mabel Infoziant: No ma please hold...
38  09/12/19                     12:42 pm - AR❤: Ok mam thank u
39  10/12/19   7:59 am - Mabel Infoziant: Ramisha we need to...
40  10/12/19   8:00 am - Mabel Infoziant: Be ready to discus...
41  10/12/19                            8:55 am - AR❤: Okay mam
42  12/12/19                      2:26 pm - Mabel Infoziant: ok
43  15/12/19                     8:22 pm - AR❤: Mam are u free?
44  15/12/19   8:40 pm - Mabel Infoziant: Am at church can c...
45  15/12/19   8:40 pm - AR❤: Kk mam. I will ask Arun brothe...
46  18/12/19                              3:09 pm - AR❤: Hi mam
47  18/12/19                    3:09 pm - AR❤: Any updates mam?
48  18/12/19   3:11 pm - Mabel Infoziant: U might have to st...
49  18/12/19   3:11 pm - Mabel Infoziant: There is one proje...
50  18/12/19                            3:12 pm - AR❤: Kk mam👍🏻

In [11]:
Message=df["Chat"].str.split("-",n=1,expand=True)

In [12]:
Message

             0                                                  1
1     1:42 pm     Mabel Infoziant: Hi this is Mabel we just spoke
2     1:42 pm              Mabel Infoziant: What’s your full name
3     1:42 pm                                 AR❤: Ramisha Rani K
4     1:42 pm                                 Mabel Infoziant: Ok
5     1:42 pm             Mabel Infoziant: ramisharanik@gmail.com
6     1:43 pm                     Mabel Infoziant: Your email Id?
7     1:43 pm                                        AR❤: Yes Mam
8     1:43 pm    Mabel Infoziant: I will send 2 abstracts for ...
9     1:43 pm                                       AR❤: Yeah mam
10    1:43 pm    Mabel Infoziant: Give me the list that u have...
11    1:43 pm    Mabel Infoziant: Send me cbe office address a...
12    1:44 pm    AR❤: Yeah Mam within Evening I will forward y...
13    1:45 pm    AR❤: Tomorrow I have to visit the office.yet ...
14    1:48 pm                                 Mabel Infoziant: ok
15    1:48 pm    Mabel Infoziant: send the details of office l...
16    1:49 pm    AR❤: Sure mam. Soon I will share details with...
17    2:00 pm    AR❤: I have read the Abstract mam. We can do ...
18    2:04 pm    Mabel Infoziant: I think Vignesh has the data...
19    2:04 pm          Mabel Infoziant: I have sent the abstracts
20    2:06 pm                                         AR❤: Ok mam
21    2:07 pm    AR❤: I have read both the abstract mam. We ca...
22    4:44 pm    Mabel Infoziant: Yes we need to ya about amou...
23    4:48 pm                                      AR❤: Sure mam.
24    8:07 pm                              AR❤: Shall I call mam?
25   10:45 pm    Mabel Infoziant: Hi I was at church couldn’t ...
26   11:52 pm                                     AR❤: It's k mam
27   11:55 pm    AR❤: Just to know the tomorrow plan mam.will ...
28   12:09 pm                AR❤: Mam can u send Vignesh number??
29   12:13 pm    Mabel Infoziant: Vignesh ML Infoziant.vcf (fi...
30   12:23 pm           Mabel Infoziant: I was in a meeting sorry
31   12:25 pm                                AR❤: Can I cal u mam
32   12:26 pm    AR❤: Waiting for u r finalization of rates fo...
33   12:26 pm    AR❤: If we finiliaze I can work with full inv...
34   12:28 pm    AR❤: So what ever may be ..if you think your ...
35   12:28 pm                       AR❤: You deleted this message
36   12:29 pm                                 AR❤: Do the needful
37   12:41 pm    Mabel Infoziant: No ma please hold I am in a ...
38   12:42 pm                                 AR❤: Ok mam thank u
39    7:59 am    Mabel Infoziant: Ramisha we need to talk toda...
40    8:00 am    Mabel Infoziant: Be ready to discuss about th...
41    8:55 am                                       AR❤: Okay mam
42    2:26 pm                                 Mabel Infoziant: ok
43    8:22 pm                                AR❤: Mam are u free?
44    8:40 pm    Mabel Infoziant: Am at church can call very l...
45    8:40 pm    AR❤: Kk mam. I will ask Arun brother. Small d...
46    3:09 pm                                         AR❤: Hi mam
47    3:09 pm                               AR❤: Any updates mam?
48    3:11 pm    Mabel Infoziant: U might have to start on the...
49    3:11 pm    Mabel Infoziant: There is one project that go...
50    3:12 pm                                       AR❤: Kk mam👍🏻

In [14]:
df["Time"]=Message[0]
Message1=Message[1].str.split(":",n=1,expand=True)

In [16]:
Message1

                   0                                                  1
1    Mabel Infoziant                     Hi this is Mabel we just spoke
2    Mabel Infoziant                              What’s your full name
3                AR❤                                     Ramisha Rani K
4    Mabel Infoziant                                                 Ok
5    Mabel Infoziant                             ramisharanik@gmail.com
6    Mabel Infoziant                                     Your email Id?
7                AR❤                                            Yes Mam
8    Mabel Infoziant     I will send 2 abstracts for u to start working
9                AR❤                                           Yeah mam
10   Mabel Infoziant                   Give me the list that u have too
11   Mabel Infoziant   Send me cbe office address and phone number I...
12               AR❤    Yeah Mam within Evening I will forward you mam.
13               AR❤   Tomorrow I have to visit the office.yet not I...
14   Mabel Infoziant                                                 ok
15   Mabel Infoziant   send the details of office location once u ge...
16               AR❤   Sure mam. Soon I will share details with you mam
17               AR❤   I have read the Abstract mam. We can do mam. ...
18   Mabel Infoziant   I think Vignesh has the data set will ask him...
19   Mabel Infoziant                          I have sent the abstracts
20               AR❤                                             Ok mam
21               AR❤   I have read both the abstract mam. We can do ...
22   Mabel Infoziant   Yes we need to ya about amount and all other ...
23               AR❤                                          Sure mam.
24               AR❤                                  Shall I call mam?
25   Mabel Infoziant         Hi I was at church couldn’t take your call
26               AR❤                                         It's k mam
27               AR❤   Just to know the tomorrow plan mam.will see t...
28               AR❤                    Mam can u send Vignesh number??
29   Mabel Infoziant           Vignesh ML Infoziant.vcf (file attached)
30   Mabel Infoziant                           I was in a meeting sorry
31               AR❤                                    Can I cal u mam
32               AR❤   Waiting for u r finalization of rates for our...
33               AR❤   If we finiliaze I can work with full involvem...
34               AR❤   So what ever may be ..if you think your are c...
35               AR❤                           You deleted this message
36               AR❤                                     Do the needful
37   Mabel Infoziant   No ma please hold I am in a hot meeting with ...
38               AR❤                                     Ok mam thank u
39   Mabel Infoziant   Ramisha we need to talk today i will call u a...
40   Mabel Infoziant     Be ready to discuss about the ML titles u have
41               AR❤                                           Okay mam
42   Mabel Infoziant                                                 ok
43               AR❤                                    Mam are u free?
44   Mabel Infoziant   Am at church can call very late or tomorrow only
45               AR❤   Kk mam. I will ask Arun brother. Small doubt ...
46               AR❤                                             Hi mam
47               AR❤                                   Any updates mam?
48   Mabel Infoziant     U might have to start on the WhatsApp analysis
49   Mabel Infoziant            There is one project that got committed
50               AR❤                                           Kk mam👍🏻

In [17]:
df["Name"]=Message1[0]

In [18]:
df["Chat"]=Message1[1]

In [19]:
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   Chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [22]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Collecting click (from nltk)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: joblib in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.2.28-cp310-cp310-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in c:\users\gnana\anaconda3\envs\myenv\lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.3-py3-none-any.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.5 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.5 MB 882.6 kB/s eta 0:00:02
   ------------- -------------------------- 0.5/1.5 MB 882.6 kB/s eta 0:00:02
   -------------------- ------------------- 0.8/1.5 MB 884.1 kB/s eta 0:00:01
   --------------------------- ------------ 1.0/1.5 MB 968.5 kB/s eta 0:00:01
   ---------------------------------- ----- 1.3/1.5 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 974.0 kB/s  0:00:01
Downloading regex-2026.2.28-cp310-cp310-win_amd64.whl (277 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, click, nltk

   ---------- ----------------------------- 1/4 [regex]
   -------------------- ------------------- 2/4 [click]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ------------------------------ --------- 3/4 [nltk]
   ---------------------------------------- 4/4 [nltk]

Successfully installed click-8.3.1 nltk-3.9.3 regex-2026.2.28 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

In [ ]:
#sentimental analysis -itself change to text to num ,topic modelling have to do change using counter vector,idf-df

In [25]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [26]:
dataset=df

In [27]:
dataset.dropna(inplace=True)

In [29]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Download (run once)
nltk.download('vader_lexicon')

# Create object
sid = SentimentIntensityAnalyzer()

# Test
text = "I am very happy today"
score = sid.polarity_scores(text)

print(score)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\gnana\AppData\Roaming\nltk_data...

{'neg': 0.0, 'neu': 0.429, 'pos': 0.571, 'compound': 0.6115}

In [30]:
 def sentimentalAnalysis(data,columnname):
        
        #downloading vader_lexicon for the process
        import matplotlib.pyplot as plt
        import seaborn as sns
        "Importing Necessary Packeage"
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        sid = SentimentIntensityAnalyzer()
        
        "Deleting null pr empty value"
        data.dropna(inplace=True)
        
        "Checking for a comment"
        #sid.polarity_scores(data[columnname][93])
        
        "Creating respective columns"
        
        data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data['compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data['Negtive']  = data['scores'].apply(lambda score_dict: score_dict['neg'])
        data['Postive']  = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data['Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        
        "Creating final pos or neg using compound score"
        data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
        plt.clf()
        #comp=sns.countplot(x = 'comp_score', hue = 'Name', data = data, palette = 'magma')
        #comp.figure.savefig("date_charts.png")
        "Checking how many pos and neg"
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [31]:
pos,data_Senti=sentimentalAnalysis(dataset,columnname='Chat')

In [32]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos

In [33]:
pos

            count
comp_score
pos            48
neg             2

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
tfidf=TfidfVectorizer(max_df=0.95,min_df=2,stop_words='english')
dtm=tfidf.fit_transform(df["Chat"])

In [36]:
from sklearn.decomposition import NMF
nmf_model=NMF(n_components=5,random_state=42)
nmf_model.fit(dtm)

NMF(n_components=5, random_state=42)

In [38]:
for index, topic in enumerate(nmf_model.components_):
    results = [tfidf.get_feature_names_out()[i] for i in topic.argsort()[-10:]]
    print(results)

['share', 'soon', 'ask', 'yes', 'sure', 'abstract', 'read', 'kk', 'yeah', 'mam']
['students', 'start', 'yes', 'think', 'sure', 'just', 'send', 'tomorrow', 'mam', 'ok']
['details', 'abstracts', 'start', 'students', 'phone', 'ask', 'office', 'number', 'vignesh', 'send']
['share', 'soon', 'yes', 'mam', 'office', 'know', 'just', 'tomorrow', 'church', 'hi']
['phone', 'know', 'sure', 'share', 'soon', 'meeting', 'details', 'yes', 'need', 'ramisha']

In [39]:
topic_results=nmf_model.transform(dtm)
df["Topic"]=topic_results.argmax(axis=1)

In [40]:
df

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score,Topic
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos,4
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,0
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos,2
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos,0
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos,2
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos,0
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,1
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos,4
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos,0
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos,3
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos,2
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg,4
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos,0
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg,4
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,4
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos,2
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos,0
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,1
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos,0
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos,0
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,3
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,2
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos,2
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos,0

In [41]:
df["Topic"].value_counts()

Topic
0    22
2    12
4     6
3     5
1     5
Name: count, dtype: int64